import Head from "next/head";
import { UilMusic } from "@iconscout/react-unicons";
import { EExternalLinks } from "../shared/utils/enums";
import { APP_NAME } from "../shared/utils/consts";

export default function Home() {
  const redirectUri =
    process.env.NODE_ENV === "development"
      ? "http://localhost:3000/authenticate"
      : `${process.env.URL}/authenticate`;
  const authenticationUrl = `${EExternalLinks.SPOTIFY_AUTH_URL}?client_id=${process.env.SPOTIFY_CLIENT_ID}&redirect_uri=${redirectUri}&response_type=token`;
  return (
    <div>
      <Head>
        <title>{APP_NAME} - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex flex-col items-center justify-center">
        <div className="flex items-center text-blue-600 mb-4">
          <UilMusic className="mr-2 w-8 h-8 animate-pulse" />{" "}
          <p className="mb-0 text-2xl font-bold">Spot</p>
        </div>
        <a
          href={authenticationUrl}
          className="bg-blue-600 transition-all hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed border-2 px-8 border-blue-600 text-blue-100  uppercase text-xs tracking-wider font-semibold py-2 rounded-md"
        >
          <p>Login with Spotify</p>
        </a>
      </main>
    </div>
  );
}
