import React from "react";
import Head from "next/head";
import PrivateLayout from "../shared/components/PrivateLayout";
import SearchWrapper from "../application/features/Search";

export default function Search() {
  return (
    <>
      <Head>
        <title>Busca</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PrivateLayout>
        <SearchWrapper />
      </PrivateLayout>
    </>
  );
}
