import React from "react";
import Head from "next/head";
import PrivateLayout from "../shared/components/PrivateLayout";
import SearchWrapper from "../application/features/Search";
import { APP_NAME } from "../shared/utils/consts";

export default function Search() {
  return (
    <>
      <Head>
        <title>{APP_NAME} - Busca</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PrivateLayout>
        <SearchWrapper />
      </PrivateLayout>
    </>
  );
}
